---
_hotel_id: BOS744
_portal_id: required-but-empty
_root_path: https://qa5.ttaws.com/rt
latitude: 42.3471
longitude: -71.07935
name: Boston Marriott Copley Place
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 110 Huntington Ave
  street2: ''
  state: Massachusetts
  city: Boston
  country: United States
  zip_code: '02116'
